import back
import start
from Tkinter import *
import sqlite3
from tkMessageBox import *
f=12
gn=0
flag=0
root1=Tk()
root1.title('phonebook')
root1['bg']='light blue'
a=PhotoImage(file='pb.gif')
Label(root1,image=a).grid(row=0,column=1)
Label(root1,text='First Name',font='times 13',bg='light blue').grid(row=1,column=0)
e1=Entry(root1)
e1.grid(row=1,column=1)
Label(root1,text='Middle Name',font='times 13',bg='light blue').grid(row=2,column=0)
e2=Entry(root1)
e2.grid(row=2,column=1)
Label(root1,text='Last Name',font='times 13',bg='light blue').grid(row=3,column=0)
e3=Entry(root1)
e3.grid(row=3,column=1)
Label(root1,text='Company Name',font='times 13 ',bg='light blue').grid(row=4,column=0)
e4=Entry(root1)
e4.grid(row=4,column=1)
Label(root1,text='Address',font='times 13',bg='light blue').grid(row=5,column=0)
e5=Entry(root1)
e5.grid(row=5,column=1)
Label(root1,text='City',font='times 13',bg='light blue').grid(row=6,column=0)
e6=Entry(root1)
e6.grid(row=6,column=1)
Label(root1,text='Pincode',font='times 13 ',bg='light blue').grid(row=7,column=0)
e7=Entry(root1)
e7.grid(row=7,column=1)
Label(root1,text='Website URl',font='times 13 ',bg='light blue').grid(row=8,column=0)
e8=Entry(root1)
e8.grid(row=8,column=1)
Label(root1,text='Date of Birth',font='times 13',bg='light blue').grid(row=9,column=0)
e9=Entry(root1)
e9.grid(row=9,column=1)
Label(root1,text='Select Phone Type:',font='times 15 bold',fg='blue',bg='light blue').grid(row=10,column=0)
v1=IntVar()
Radiobutton(root1,text='Office',variable=v1,value=1,bg='light blue').grid(row=10,column=1)
Radiobutton(root1,text='Home',variable=v1,value=2,bg='light blue').grid(row=10,column=2)
Radiobutton(root1,text='Mobile',variable=v1,value=3,bg='light blue').grid(row=10,column=3)
Label(root1,text='Phone Number',font='times 13 ',bg='light blue').grid(row=11,column=0)
e10=Entry(root1)
e10.grid(row=11,column=1)
Button(root1,text='+',command=anc).grid(row=11,column=2)
Label(root1,text='Select Email Type:',font='times 15 bold ',fg='blue',bg='light blue').grid(row=f+2,column=0)
v2=IntVar()
Radiobutton(root1,text='Office',variable=v2,value=1,bg='light blue').grid(row=f+2,column=1)
Radiobutton(root1,text='Personal',variable=v2,value=2,bg='light blue').grid(row=f+2,column=2)
Label(root1,text='Email id',font='times 13 ',bg='light blue').grid(row=f+3,column=0)
e11=Entry(root1)
e11.grid(row=f+3,column=1)
Button(root1,text='+').grid(row=f+3,column=2)
Button(root1,text='Save',command=save).grid(row=f+4,column=0)
Button(root1,text='Search',command=search).grid(row=f+4,column=1)
Button(root1,text='Close',command=close).grid(row=f+4,column=2)
Button(root1,text='Edit',command=search).grid(row=f+4,column=3)    
root1.mainloop()
